name: Test

env:
    RUST_BACKTRACE: 1

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Rust components
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt, rustc-dev, llvm-tools-preview
    - name: Build with cargo
      run: cargo build --all --verbose
    - name: Run cargo tests
      run: cargo test --all --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check extractor
      run: python3 extractor-test/test_extractor.py
